# Generated by Django 3.0.5 on 2022-08-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=40)),
                ('payment_type', models.CharField(max_length=40)),
                ('account_no', models.PositiveIntegerField()),
                ('transaction_id', models.PositiveIntegerField()),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payments/receipts/')),
            ],
        ),
    ]
