# Generated by Django 3.0.5 on 2022-08-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankNamLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=40)),
            ],
        ),
    ]
