# Generated by Django 3.0.5 on 2022-08-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_banknamlists'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankNamLists',
            new_name='BankNameLists',
        ),
    ]
