# Generated by Django 3.0.5 on 2022-08-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20220809_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bank_name',
        ),
    ]
