# Generated by Django 3.0.5 on 2022-08-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20220809_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='account_no',
            field=models.BigIntegerField(),
        ),
    ]
