# Generated by Django 3.0.5 on 2022-08-04 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpolicy_name', models.CharField(max_length=50)),
                ('proposer_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=80)),
                ('phone_no', models.PositiveIntegerField()),
                ('pobox', models.PositiveIntegerField()),
                ('licenceno', models.PositiveIntegerField()),
                ('durationfrom', models.CharField(max_length=50)),
                ('durationto', models.CharField(max_length=50)),
                ('plateno', models.CharField(max_length=10)),
                ('vehiclename', models.CharField(max_length=50)),
                ('vehiclemodel', models.CharField(max_length=50)),
                ('yearofmanufacture', models.CharField(max_length=50)),
                ('yearofpurchase', models.CharField(max_length=50)),
                ('priceofcar', models.CharField(max_length=50)),
                ('creation_date', models.DateField(auto_now=True)),
                ('vehicle_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Category')),
            ],
        ),
    ]
