# Generated by Django 3.0.5 on 2022-08-18 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20220810_0931'),
        ('manager', '0006_auto_20220809_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_policy',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='vehicle_policy',
            name='policychoice',
            field=models.CharField(choices=[('Comprehensive', 'ሁሉን አቀፍ'), ('Third Party only', 'የሶስተኛ ወገን ብቻ'), ('Third Party, Fire and Theft', 'የሶስተኛ ወገን, እሳት እና ስርቆት')], default='Comprehensive', max_length=40),
        ),
    ]
