# Generated by Django 3.0.5 on 2022-08-22 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20220810_0931'),
        ('manager', '0008_auto_20220818_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='claim_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now=True)),
                ('insured_name', models.CharField(max_length=50)),
                ('phone_no', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=80)),
                ('policy_number', models.PositiveIntegerField()),
                ('renewal_date', models.DateField()),
                ('vehiclemodel', models.CharField(max_length=50)),
                ('yearofmanufacture', models.CharField(max_length=50)),
                ('plateno', models.CharField(max_length=10)),
                ('licenceno', models.PositiveIntegerField()),
                ('vehicle_purpose', models.CharField(max_length=50)),
                ('horsepower', models.CharField(max_length=50)),
                ('carrying_capacity', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=50)),
                ('driver_age', models.PositiveIntegerField()),
                ('driver_phone_no', models.PositiveIntegerField()),
                ('driver_address', models.CharField(max_length=50)),
                ('licence_number', models.CharField(max_length=50)),
                ('driver_profession', models.CharField(max_length=80)),
                ('licence_grade', models.PositiveIntegerField()),
                ('licence_expiry_date', models.DateField()),
                ('accident_date', models.DateField()),
                ('accident_time', models.CharField(max_length=10)),
                ('accident_place', models.CharField(max_length=40)),
                ('accident_description', models.CharField(max_length=500)),
                ('accident_proof', models.ImageField(blank=True, null=True, upload_to='accident_pic/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('vehicle_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Category')),
            ],
        ),
    ]
