# Generated by Django 3.0.5 on 2022-08-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_claim_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_policy',
            name='vehicle_policy',
        ),
        migrations.RemoveField(
            model_name='vehicle_policy',
            name='vpolicy_name',
        ),
    ]
