# Generated by Django 3.0.5 on 2022-08-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20220822_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_policy',
            name='phone_no',
            field=models.BigIntegerField(),
        ),
    ]
