# Generated by Django 3.0.5 on 2022-08-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20220822_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Subject', models.CharField(max_length=70)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
    ]
