# Generated by Django 3.0.5 on 2022-08-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_vehicle_policy_policy_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_policy',
            name='policy_number',
            field=models.CharField(max_length=15),
        ),
    ]
