# Generated by Django 3.0.5 on 2022-08-26 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_auto_20220826_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim_form',
            old_name='vehicle_policy',
            new_name='policy_type',
        ),
    ]
