# Generated by Django 3.0.5 on 2022-08-26 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20220810_0931'),
        ('manager', '0015_auto_20220826_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply_claims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='creation_datee', to='manager.vehicle_policy')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('durationfrom', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='durationfromm', to='manager.vehicle_policy')),
                ('durationto', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='durationtoo', to='manager.vehicle_policy')),
                ('policy_number', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='policy_numberr', to='manager.vehicle_policy')),
            ],
        ),
        migrations.CreateModel(
            name='claim_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClaimType', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='claim_form',
            name='policy_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.vehicle_policy'),
        ),
        migrations.CreateModel(
            name='ClaimRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('creation_date', models.DateField(auto_now=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.apply_claims')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='apply_claims',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.claim_type'),
        ),
        migrations.AddField(
            model_name='apply_claims',
            name='vehiclemodel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='vehiclemodell', to='manager.vehicle_policy'),
        ),
        migrations.AddField(
            model_name='apply_claims',
            name='vehiclename',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='vehiclenamee', to='manager.vehicle_policy'),
        ),
    ]
