# Generated by Django 3.0.5 on 2022-08-26 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_auto_20220826_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_claims',
            name='creation_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creation_date', to='manager.vehicle_policy'),
        ),
        migrations.AlterField(
            model_name='apply_claims',
            name='durationfrom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Durationfrom', to='manager.vehicle_policy'),
        ),
        migrations.AlterField(
            model_name='apply_claims',
            name='durationto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Durationto', to='manager.vehicle_policy'),
        ),
        migrations.AlterField(
            model_name='apply_claims',
            name='policy_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Policy_number', to='manager.vehicle_policy'),
        ),
        migrations.AlterField(
            model_name='apply_claims',
            name='vehiclemodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehiclemodel', to='manager.vehicle_policy'),
        ),
        migrations.AlterField(
            model_name='apply_claims',
            name='vehiclename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vehiclename', to='manager.vehicle_policy'),
        ),
    ]
