# Generated by Django 3.0.5 on 2022-08-26 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_addclaim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimrecord',
            name='claim',
        ),
        migrations.RemoveField(
            model_name='claimrecord',
            name='customer',
        ),
        migrations.DeleteModel(
            name='apply_claims',
        ),
        migrations.DeleteModel(
            name='ClaimRecord',
        ),
    ]
